import Foundation

// MARK: - Designer Themes: Bold, distinctive personalities

extension Theme {

    // MARK: - 1. Midnight Rose (Dark — romantic navy with dusty pink)
    static let midnightRose = Theme(
        metadata: ThemeMetadata(id: "midnight-rose", name: "Midnight Rose", author: "Deck", version: 1, colorScheme: .dark, description: "Deep navy ink with dusty rose accents", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "0F1219"), inset: ThemeColor(hex: "0A0D14"), elevated: ThemeColor(hex: "171C26"), overlay: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0.65), hover: ThemeColor(hex: "1E2433"), active: ThemeColor(hex: "252B3C"), selected: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.12), selectedHover: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.18), bar: ThemeColor(hex: "0A0D14"), subtle: ThemeColor(red: 1, green: 1, blue: 1, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "1E2433"), hover: ThemeColor(hex: "2D3548"), selected: ThemeColor(hex: "D4748A"), focused: ThemeColor(hex: "D4748A"), subtle: ThemeColor(red: 1, green: 1, blue: 1, opacity: 0.06), error: ThemeColor(hex: "EF4444"), warning: ThemeColor(hex: "F59E0B")),
        text: TextColors(primary: ThemeColor(hex: "E8E2E4"), secondary: ThemeColor(hex: "9B8F95"), tertiary: ThemeColor(hex: "6B6068"), quaternary: ThemeColor(hex: "4A4248"), onAccent: ThemeColor(hex: "FFFFFF"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "E8A0B0")),
        icons: IconColors(primary: ThemeColor(hex: "C8BCC2"), secondary: ThemeColor(hex: "6B6068"), tertiary: ThemeColor(hex: "4A4248"), onAccent: ThemeColor(hex: "FFFFFF")),
        accent: AccentColors(primary: ThemeColor(hex: "D4748A"), hover: ThemeColor(hex: "E8A0B0"), active: ThemeColor(hex: "B85670"), subtle: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.15), muted: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.08)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "EF4444"), subtle: ThemeColor(hex: "3B1818"), border: ThemeColor(red: 0.94, green: 0.27, blue: 0.27, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "F59E0B"), subtle: ThemeColor(hex: "3B2E10"), border: ThemeColor(red: 0.96, green: 0.62, blue: 0.04, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "22C55E"), subtle: ThemeColor(hex: "14332A"), border: ThemeColor(red: 0.13, green: 0.77, blue: 0.37, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "0EA5E9"), subtle: ThemeColor(hex: "0C2D48"), border: ThemeColor(red: 0.05, green: 0.65, blue: 0.91, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "D4748A"), scrollbarThumb: ThemeColor(hex: "2D3548"), scrollbarThumbHover: ThemeColor(hex: "3D475C"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.30), searchMatchActive: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.60), dropTarget: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "D4748A")),
        terminal: TerminalColors(background: ThemeColor(hex: "0F1219"), foreground: ThemeColor(hex: "E8E2E4"), cursor: ThemeColor(hex: "D4748A"), cursorText: ThemeColor(hex: "0F1219"), selection: ThemeColor(red: 0.85, green: 0.45, blue: 0.55, opacity: 0.25), ansi: AnsiPalette(black: ThemeColor(hex: "1E2433"), red: ThemeColor(hex: "E8707A"), green: ThemeColor(hex: "8BC89A"), yellow: ThemeColor(hex: "E8C880"), blue: ThemeColor(hex: "7AAAE8"), magenta: ThemeColor(hex: "D4748A"), cyan: ThemeColor(hex: "6EC8C8"), white: ThemeColor(hex: "C8BCC2"), brightBlack: ThemeColor(hex: "3D475C"), brightRed: ThemeColor(hex: "F0A0A8"), brightGreen: ThemeColor(hex: "A8E0B8"), brightYellow: ThemeColor(hex: "F0DCA0"), brightBlue: ThemeColor(hex: "A0C8F0"), brightMagenta: ThemeColor(hex: "E8A0B0"), brightCyan: ThemeColor(hex: "90E0E0"), brightWhite: ThemeColor(hex: "F0E8EC")))
    )

    // MARK: - 2. Matrix (Green phosphor on true black)
    static let matcha = Theme(
        metadata: ThemeMetadata(id: "matrix", name: "Matrix", author: "Deck", version: 1, colorScheme: .dark, description: "Green phosphor terminal — the one and only", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "000000"), inset: ThemeColor(hex: "000000"), elevated: ThemeColor(hex: "0A1A0A"), overlay: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0.80), hover: ThemeColor(hex: "0D200D"), active: ThemeColor(hex: "102810"), selected: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.08), selectedHover: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.14), bar: ThemeColor(hex: "000000"), subtle: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "0D300D"), hover: ThemeColor(hex: "1A4A1A"), selected: ThemeColor(hex: "00FF33"), focused: ThemeColor(hex: "00FF33"), subtle: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.08), error: ThemeColor(hex: "FF3333"), warning: ThemeColor(hex: "CCCC00")),
        text: TextColors(primary: ThemeColor(hex: "00FF33"), secondary: ThemeColor(hex: "00BB22"), tertiary: ThemeColor(hex: "008818"), quaternary: ThemeColor(hex: "005510"), onAccent: ThemeColor(hex: "000000"), onError: ThemeColor(hex: "000000"), link: ThemeColor(hex: "33FF66")),
        icons: IconColors(primary: ThemeColor(hex: "00DD2B"), secondary: ThemeColor(hex: "008818"), tertiary: ThemeColor(hex: "005510"), onAccent: ThemeColor(hex: "000000")),
        accent: AccentColors(primary: ThemeColor(hex: "00FF33"), hover: ThemeColor(hex: "33FF66"), active: ThemeColor(hex: "00CC28"), subtle: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.15), muted: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.06)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "FF3333"), subtle: ThemeColor(hex: "1A0000"), border: ThemeColor(red: 1, green: 0.2, blue: 0.2, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "CCCC00"), subtle: ThemeColor(hex: "1A1A00"), border: ThemeColor(red: 0.8, green: 0.8, blue: 0, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "00FF33"), subtle: ThemeColor(hex: "001A08"), border: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "33CCFF"), subtle: ThemeColor(hex: "001A22"), border: ThemeColor(red: 0.2, green: 0.8, blue: 1, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "00FF33"), scrollbarThumb: ThemeColor(hex: "0D300D"), scrollbarThumbHover: ThemeColor(hex: "1A4A1A"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.30), searchMatchActive: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.60), dropTarget: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "00FF33")),
        terminal: TerminalColors(background: ThemeColor(hex: "000000"), foreground: ThemeColor(hex: "00FF33"), cursor: ThemeColor(hex: "00FF33"), cursorText: ThemeColor(hex: "000000"), selection: ThemeColor(red: 0, green: 1, blue: 0.2, opacity: 0.20), ansi: AnsiPalette(black: ThemeColor(hex: "0A1A0A"), red: ThemeColor(hex: "FF3333"), green: ThemeColor(hex: "00FF33"), yellow: ThemeColor(hex: "CCCC00"), blue: ThemeColor(hex: "3399FF"), magenta: ThemeColor(hex: "CC33FF"), cyan: ThemeColor(hex: "33CCCC"), white: ThemeColor(hex: "00DD2B"), brightBlack: ThemeColor(hex: "1A4A1A"), brightRed: ThemeColor(hex: "FF6666"), brightGreen: ThemeColor(hex: "66FF88"), brightYellow: ThemeColor(hex: "FFFF33"), brightBlue: ThemeColor(hex: "66BBFF"), brightMagenta: ThemeColor(hex: "DD66FF"), brightCyan: ThemeColor(hex: "66EEDD"), brightWhite: ThemeColor(hex: "33FF66")))
    )

    // MARK: - 3. Swiss (Stark white, Helvetica-inspired minimal)
    static let cosmos = Theme(
        metadata: ThemeMetadata(id: "swiss", name: "Swiss", author: "Deck", version: 1, colorScheme: .light, description: "Stark, clean, Helvetica-inspired minimalism", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "FFFFFF"), inset: ThemeColor(hex: "F5F5F5"), elevated: ThemeColor(hex: "FFFFFF"), overlay: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0.15), hover: ThemeColor(hex: "F0F0F0"), active: ThemeColor(hex: "E8E8E8"), selected: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.06), selectedHover: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.10), bar: ThemeColor(hex: "F5F5F5"), subtle: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0.02)),
        borders: BorderColors(primary: ThemeColor(hex: "E0E0E0"), hover: ThemeColor(hex: "CCCCCC"), selected: ThemeColor(hex: "FF0000"), focused: ThemeColor(hex: "FF0000"), subtle: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0.06), error: ThemeColor(hex: "FF0000"), warning: ThemeColor(hex: "FF8800")),
        text: TextColors(primary: ThemeColor(hex: "000000"), secondary: ThemeColor(hex: "555555"), tertiary: ThemeColor(hex: "888888"), quaternary: ThemeColor(hex: "BBBBBB"), onAccent: ThemeColor(hex: "FFFFFF"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "FF0000")),
        icons: IconColors(primary: ThemeColor(hex: "333333"), secondary: ThemeColor(hex: "888888"), tertiary: ThemeColor(hex: "BBBBBB"), onAccent: ThemeColor(hex: "FFFFFF")),
        accent: AccentColors(primary: ThemeColor(hex: "FF0000"), hover: ThemeColor(hex: "CC0000"), active: ThemeColor(hex: "990000"), subtle: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.08), muted: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.04)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "FF0000"), subtle: ThemeColor(hex: "FFF0F0"), border: ThemeColor(hex: "FFCCCC")), warning: StatusColor(primary: ThemeColor(hex: "FF8800"), subtle: ThemeColor(hex: "FFF5E6"), border: ThemeColor(hex: "FFD699")), success: StatusColor(primary: ThemeColor(hex: "00AA44"), subtle: ThemeColor(hex: "E6FFE6"), border: ThemeColor(hex: "99DDAA")), info: StatusColor(primary: ThemeColor(hex: "0066CC"), subtle: ThemeColor(hex: "E6F0FF"), border: ThemeColor(hex: "99BBEE"))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "FF0000"), scrollbarThumb: ThemeColor(hex: "CCCCCC"), scrollbarThumbHover: ThemeColor(hex: "AAAAAA"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.15), searchMatchActive: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.30), dropTarget: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.05), dropTargetBorder: ThemeColor(hex: "FF0000")),
        terminal: TerminalColors(background: ThemeColor(hex: "FFFFFF"), foreground: ThemeColor(hex: "000000"), cursor: ThemeColor(hex: "FF0000"), cursorText: ThemeColor(hex: "FFFFFF"), selection: ThemeColor(red: 1, green: 0, blue: 0, opacity: 0.12), ansi: AnsiPalette(black: ThemeColor(hex: "000000"), red: ThemeColor(hex: "CC0000"), green: ThemeColor(hex: "008800"), yellow: ThemeColor(hex: "886600"), blue: ThemeColor(hex: "0044CC"), magenta: ThemeColor(hex: "880088"), cyan: ThemeColor(hex: "006688"), white: ThemeColor(hex: "888888"), brightBlack: ThemeColor(hex: "555555"), brightRed: ThemeColor(hex: "FF0000"), brightGreen: ThemeColor(hex: "00BB00"), brightYellow: ThemeColor(hex: "BB8800"), brightBlue: ThemeColor(hex: "0066FF"), brightMagenta: ThemeColor(hex: "BB00BB"), brightCyan: ThemeColor(hex: "0088BB"), brightWhite: ThemeColor(hex: "000000")))
    )

    // MARK: - 4. Hickory (Warm wood tones, cream and amber)
    static let copper = Theme(
        metadata: ThemeMetadata(id: "hickory", name: "Hickory", author: "Deck", version: 1, colorScheme: .dark, description: "Warm wood tones — amber, cream, and brown", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "1C1610"), inset: ThemeColor(hex: "14100A"), elevated: ThemeColor(hex: "261E16"), overlay: ThemeColor(red: 0.06, green: 0.04, blue: 0.02, opacity: 0.70), hover: ThemeColor(hex: "30261C"), active: ThemeColor(hex: "3A2E22"), selected: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.12), selectedHover: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.18), bar: ThemeColor(hex: "14100A"), subtle: ThemeColor(red: 1, green: 0.9, blue: 0.7, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "30261C"), hover: ThemeColor(hex: "4A3C2E"), selected: ThemeColor(hex: "D99940"), focused: ThemeColor(hex: "D99940"), subtle: ThemeColor(red: 1, green: 0.9, blue: 0.7, opacity: 0.06), error: ThemeColor(hex: "E05540"), warning: ThemeColor(hex: "D99940")),
        text: TextColors(primary: ThemeColor(hex: "F0E6D6"), secondary: ThemeColor(hex: "B8A890"), tertiary: ThemeColor(hex: "8A7A68"), quaternary: ThemeColor(hex: "5C5040"), onAccent: ThemeColor(hex: "1C1610"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "E8B050")),
        icons: IconColors(primary: ThemeColor(hex: "D4C4B0"), secondary: ThemeColor(hex: "8A7A68"), tertiary: ThemeColor(hex: "5C5040"), onAccent: ThemeColor(hex: "1C1610")),
        accent: AccentColors(primary: ThemeColor(hex: "D99940"), hover: ThemeColor(hex: "E8B060"), active: ThemeColor(hex: "C08030"), subtle: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.15), muted: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.08)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "E05540"), subtle: ThemeColor(hex: "301510"), border: ThemeColor(red: 0.88, green: 0.33, blue: 0.25, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "D99940"), subtle: ThemeColor(hex: "302010"), border: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "7ABB55"), subtle: ThemeColor(hex: "1A2A10"), border: ThemeColor(red: 0.48, green: 0.73, blue: 0.33, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "55AACC"), subtle: ThemeColor(hex: "0A2030"), border: ThemeColor(red: 0.33, green: 0.67, blue: 0.80, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "D99940"), scrollbarThumb: ThemeColor(hex: "3A2E22"), scrollbarThumbHover: ThemeColor(hex: "4A3C2E"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.30), searchMatchActive: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.60), dropTarget: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "D99940")),
        terminal: TerminalColors(background: ThemeColor(hex: "1C1610"), foreground: ThemeColor(hex: "F0E6D6"), cursor: ThemeColor(hex: "D99940"), cursorText: ThemeColor(hex: "1C1610"), selection: ThemeColor(red: 0.85, green: 0.60, blue: 0.25, opacity: 0.20), ansi: AnsiPalette(black: ThemeColor(hex: "30261C"), red: ThemeColor(hex: "E06050"), green: ThemeColor(hex: "88BB55"), yellow: ThemeColor(hex: "D9A040"), blue: ThemeColor(hex: "6699CC"), magenta: ThemeColor(hex: "BB7788"), cyan: ThemeColor(hex: "66AABB"), white: ThemeColor(hex: "D4C4B0"), brightBlack: ThemeColor(hex: "5C5040"), brightRed: ThemeColor(hex: "F08878"), brightGreen: ThemeColor(hex: "A8DD77"), brightYellow: ThemeColor(hex: "E8C070"), brightBlue: ThemeColor(hex: "88BBDD"), brightMagenta: ThemeColor(hex: "DD99AA"), brightCyan: ThemeColor(hex: "88CCDD"), brightWhite: ThemeColor(hex: "F5EEE0")))
    )

    // MARK: - 5. Arctic (Ice blue on pure white)
    static let arctic = Theme(
        metadata: ThemeMetadata(id: "arctic", name: "Arctic", author: "Deck", version: 1, colorScheme: .light, description: "Crisp ice blue on clean white", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "FAFCFF"), inset: ThemeColor(hex: "F0F4FA"), elevated: ThemeColor(hex: "FFFFFF"), overlay: ThemeColor(red: 0, green: 0.1, blue: 0.2, opacity: 0.12), hover: ThemeColor(hex: "EDF2F9"), active: ThemeColor(hex: "E0E8F2"), selected: ThemeColor(red: 0.2, green: 0.5, blue: 0.9, opacity: 0.10), selectedHover: ThemeColor(red: 0.2, green: 0.5, blue: 0.9, opacity: 0.15), bar: ThemeColor(hex: "F0F4FA"), subtle: ThemeColor(red: 0, green: 0.2, blue: 0.5, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "D6E0ED"), hover: ThemeColor(hex: "B8C8DD"), selected: ThemeColor(hex: "2E7DD6"), focused: ThemeColor(hex: "2E7DD6"), subtle: ThemeColor(red: 0, green: 0.2, blue: 0.5, opacity: 0.08), error: ThemeColor(hex: "DC4444"), warning: ThemeColor(hex: "DD8800")),
        text: TextColors(primary: ThemeColor(hex: "1A2A3E"), secondary: ThemeColor(hex: "5A6A7E"), tertiary: ThemeColor(hex: "8A96A6"), quaternary: ThemeColor(hex: "B0BAC6"), onAccent: ThemeColor(hex: "FFFFFF"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "2E7DD6")),
        icons: IconColors(primary: ThemeColor(hex: "3A4E66"), secondary: ThemeColor(hex: "8A96A6"), tertiary: ThemeColor(hex: "B0BAC6"), onAccent: ThemeColor(hex: "FFFFFF")),
        accent: AccentColors(primary: ThemeColor(hex: "2E7DD6"), hover: ThemeColor(hex: "1A6BC4"), active: ThemeColor(hex: "1558AA"), subtle: ThemeColor(red: 0.2, green: 0.5, blue: 0.85, opacity: 0.10), muted: ThemeColor(red: 0.2, green: 0.5, blue: 0.85, opacity: 0.05)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "DC4444"), subtle: ThemeColor(hex: "FFF0F0"), border: ThemeColor(hex: "FFCCCC")), warning: StatusColor(primary: ThemeColor(hex: "DD8800"), subtle: ThemeColor(hex: "FFF6E6"), border: ThemeColor(hex: "FFDD99")), success: StatusColor(primary: ThemeColor(hex: "22AA55"), subtle: ThemeColor(hex: "F0FFF0"), border: ThemeColor(hex: "AADDAA")), info: StatusColor(primary: ThemeColor(hex: "2E7DD6"), subtle: ThemeColor(hex: "F0F6FF"), border: ThemeColor(hex: "AAC8EE"))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "2E7DD6"), scrollbarThumb: ThemeColor(hex: "C0CAD6"), scrollbarThumbHover: ThemeColor(hex: "A0AEBB"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.2, green: 0.5, blue: 0.85, opacity: 0.15), searchMatchActive: ThemeColor(red: 0.2, green: 0.5, blue: 0.85, opacity: 0.35), dropTarget: ThemeColor(red: 0.2, green: 0.5, blue: 0.85, opacity: 0.08), dropTargetBorder: ThemeColor(hex: "2E7DD6")),
        terminal: TerminalColors(background: ThemeColor(hex: "FAFCFF"), foreground: ThemeColor(hex: "1A2A3E"), cursor: ThemeColor(hex: "2E7DD6"), cursorText: ThemeColor(hex: "FFFFFF"), selection: ThemeColor(red: 0.2, green: 0.5, blue: 0.85, opacity: 0.15), ansi: AnsiPalette(black: ThemeColor(hex: "1A2A3E"), red: ThemeColor(hex: "CC3333"), green: ThemeColor(hex: "228844"), yellow: ThemeColor(hex: "997700"), blue: ThemeColor(hex: "2266CC"), magenta: ThemeColor(hex: "8844AA"), cyan: ThemeColor(hex: "226688"), white: ThemeColor(hex: "8A96A6"), brightBlack: ThemeColor(hex: "5A6A7E"), brightRed: ThemeColor(hex: "EE4444"), brightGreen: ThemeColor(hex: "33AA55"), brightYellow: ThemeColor(hex: "BB9900"), brightBlue: ThemeColor(hex: "3388EE"), brightMagenta: ThemeColor(hex: "AA55CC"), brightCyan: ThemeColor(hex: "3388AA"), brightWhite: ThemeColor(hex: "1A2A3E")))
    )

    // MARK: - 6. Sakura (Light — soft pink cherry blossom)
    static let sakura = Theme(
        metadata: ThemeMetadata(id: "sakura", name: "Sakura", author: "Deck", version: 1, colorScheme: .light, description: "Soft cherry blossom pink on warm white", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "FFF8F6"), inset: ThemeColor(hex: "FFF0ED"), elevated: ThemeColor(hex: "FFFFFF"), overlay: ThemeColor(red: 0.2, green: 0, blue: 0, opacity: 0.10), hover: ThemeColor(hex: "FFECE8"), active: ThemeColor(hex: "FFE0DA"), selected: ThemeColor(red: 0.9, green: 0.3, blue: 0.4, opacity: 0.08), selectedHover: ThemeColor(red: 0.9, green: 0.3, blue: 0.4, opacity: 0.14), bar: ThemeColor(hex: "FFF0ED"), subtle: ThemeColor(red: 0.9, green: 0.2, blue: 0.3, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "F0D4D0"), hover: ThemeColor(hex: "E8B8B2"), selected: ThemeColor(hex: "E85670"), focused: ThemeColor(hex: "E85670"), subtle: ThemeColor(red: 0.9, green: 0.3, blue: 0.4, opacity: 0.10), error: ThemeColor(hex: "DD3344"), warning: ThemeColor(hex: "DD8833")),
        text: TextColors(primary: ThemeColor(hex: "3A2028"), secondary: ThemeColor(hex: "7A5A62"), tertiary: ThemeColor(hex: "A88A92"), quaternary: ThemeColor(hex: "C8B0B6"), onAccent: ThemeColor(hex: "FFFFFF"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "D84060")),
        icons: IconColors(primary: ThemeColor(hex: "5A3840"), secondary: ThemeColor(hex: "A88A92"), tertiary: ThemeColor(hex: "C8B0B6"), onAccent: ThemeColor(hex: "FFFFFF")),
        accent: AccentColors(primary: ThemeColor(hex: "E85670"), hover: ThemeColor(hex: "D44060"), active: ThemeColor(hex: "C03050"), subtle: ThemeColor(red: 0.9, green: 0.33, blue: 0.44, opacity: 0.10), muted: ThemeColor(red: 0.9, green: 0.33, blue: 0.44, opacity: 0.05)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "DD3344"), subtle: ThemeColor(hex: "FFF0F0"), border: ThemeColor(hex: "FFCCCC")), warning: StatusColor(primary: ThemeColor(hex: "DD8833"), subtle: ThemeColor(hex: "FFF6EE"), border: ThemeColor(hex: "FFDDAA")), success: StatusColor(primary: ThemeColor(hex: "44AA66"), subtle: ThemeColor(hex: "F0FFF0"), border: ThemeColor(hex: "AADDBB")), info: StatusColor(primary: ThemeColor(hex: "4488CC"), subtle: ThemeColor(hex: "F0F6FF"), border: ThemeColor(hex: "AACCEE"))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "E85670"), scrollbarThumb: ThemeColor(hex: "D8C0BC"), scrollbarThumbHover: ThemeColor(hex: "C0A0A0"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.9, green: 0.33, blue: 0.44, opacity: 0.15), searchMatchActive: ThemeColor(red: 0.9, green: 0.33, blue: 0.44, opacity: 0.35), dropTarget: ThemeColor(red: 0.9, green: 0.33, blue: 0.44, opacity: 0.08), dropTargetBorder: ThemeColor(hex: "E85670")),
        terminal: TerminalColors(background: ThemeColor(hex: "FFF8F6"), foreground: ThemeColor(hex: "3A2028"), cursor: ThemeColor(hex: "E85670"), cursorText: ThemeColor(hex: "FFFFFF"), selection: ThemeColor(red: 0.9, green: 0.33, blue: 0.44, opacity: 0.15), ansi: AnsiPalette(black: ThemeColor(hex: "3A2028"), red: ThemeColor(hex: "CC3344"), green: ThemeColor(hex: "448844"), yellow: ThemeColor(hex: "997744"), blue: ThemeColor(hex: "4466BB"), magenta: ThemeColor(hex: "AA4488"), cyan: ThemeColor(hex: "447788"), white: ThemeColor(hex: "A88A92"), brightBlack: ThemeColor(hex: "7A5A62"), brightRed: ThemeColor(hex: "EE4455"), brightGreen: ThemeColor(hex: "55AA66"), brightYellow: ThemeColor(hex: "BB9955"), brightBlue: ThemeColor(hex: "5588DD"), brightMagenta: ThemeColor(hex: "CC55AA"), brightCyan: ThemeColor(hex: "5599AA"), brightWhite: ThemeColor(hex: "3A2028")))
    )

    // MARK: - 7. Void (True OLED black, minimal purple accent)
    static let void = Theme(
        metadata: ThemeMetadata(id: "void", name: "Void", author: "Deck", version: 1, colorScheme: .dark, description: "True OLED black with subtle violet", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "000000"), inset: ThemeColor(hex: "000000"), elevated: ThemeColor(hex: "0A0A10"), overlay: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0.80), hover: ThemeColor(hex: "101018"), active: ThemeColor(hex: "18181F"), selected: ThemeColor(red: 0.5, green: 0.3, blue: 1, opacity: 0.10), selectedHover: ThemeColor(red: 0.5, green: 0.3, blue: 1, opacity: 0.15), bar: ThemeColor(hex: "000000"), subtle: ThemeColor(red: 0.5, green: 0.3, blue: 1, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "18181F"), hover: ThemeColor(hex: "252530"), selected: ThemeColor(hex: "7C5CFC"), focused: ThemeColor(hex: "7C5CFC"), subtle: ThemeColor(red: 1, green: 1, blue: 1, opacity: 0.04), error: ThemeColor(hex: "F04050"), warning: ThemeColor(hex: "E0A020")),
        text: TextColors(primary: ThemeColor(hex: "E8E8F0"), secondary: ThemeColor(hex: "8888A0"), tertiary: ThemeColor(hex: "555568"), quaternary: ThemeColor(hex: "333340"), onAccent: ThemeColor(hex: "FFFFFF"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "A088FF")),
        icons: IconColors(primary: ThemeColor(hex: "B0B0C8"), secondary: ThemeColor(hex: "555568"), tertiary: ThemeColor(hex: "333340"), onAccent: ThemeColor(hex: "FFFFFF")),
        accent: AccentColors(primary: ThemeColor(hex: "7C5CFC"), hover: ThemeColor(hex: "9B80FF"), active: ThemeColor(hex: "6040DD"), subtle: ThemeColor(red: 0.5, green: 0.36, blue: 0.99, opacity: 0.15), muted: ThemeColor(red: 0.5, green: 0.36, blue: 0.99, opacity: 0.06)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "F04050"), subtle: ThemeColor(hex: "200808"), border: ThemeColor(red: 0.94, green: 0.25, blue: 0.31, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "E0A020"), subtle: ThemeColor(hex: "201808"), border: ThemeColor(red: 0.88, green: 0.63, blue: 0.13, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "30CC60"), subtle: ThemeColor(hex: "082010"), border: ThemeColor(red: 0.19, green: 0.80, blue: 0.38, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "40A0E8"), subtle: ThemeColor(hex: "081820"), border: ThemeColor(red: 0.25, green: 0.63, blue: 0.91, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "7C5CFC"), scrollbarThumb: ThemeColor(hex: "18181F"), scrollbarThumbHover: ThemeColor(hex: "252530"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.5, green: 0.36, blue: 0.99, opacity: 0.25), searchMatchActive: ThemeColor(red: 0.5, green: 0.36, blue: 0.99, opacity: 0.50), dropTarget: ThemeColor(red: 0.5, green: 0.36, blue: 0.99, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "7C5CFC")),
        terminal: TerminalColors(background: ThemeColor(hex: "000000"), foreground: ThemeColor(hex: "E8E8F0"), cursor: ThemeColor(hex: "7C5CFC"), cursorText: ThemeColor(hex: "000000"), selection: ThemeColor(red: 0.5, green: 0.36, blue: 0.99, opacity: 0.20), ansi: AnsiPalette(black: ThemeColor(hex: "18181F"), red: ThemeColor(hex: "F06070"), green: ThemeColor(hex: "50CC70"), yellow: ThemeColor(hex: "E0C040"), blue: ThemeColor(hex: "5090F0"), magenta: ThemeColor(hex: "B070F0"), cyan: ThemeColor(hex: "50C0D0"), white: ThemeColor(hex: "B0B0C8"), brightBlack: ThemeColor(hex: "333340"), brightRed: ThemeColor(hex: "FF8890"), brightGreen: ThemeColor(hex: "70EE90"), brightYellow: ThemeColor(hex: "FFE060"), brightBlue: ThemeColor(hex: "70B0FF"), brightMagenta: ThemeColor(hex: "D090FF"), brightCyan: ThemeColor(hex: "70E0F0"), brightWhite: ThemeColor(hex: "F0F0FF")))
    )

    // MARK: - 8. Dune (Sandy warm tones — desert sunset)
    static let dune = Theme(
        metadata: ThemeMetadata(id: "dune", name: "Dune", author: "Deck", version: 1, colorScheme: .dark, description: "Desert sand tones with warm orange sunset", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "1A1512"), inset: ThemeColor(hex: "12100C"), elevated: ThemeColor(hex: "241E18"), overlay: ThemeColor(red: 0.05, green: 0.03, blue: 0.01, opacity: 0.70), hover: ThemeColor(hex: "2E2620"), active: ThemeColor(hex: "383028"), selected: ThemeColor(red: 0.95, green: 0.50, blue: 0.15, opacity: 0.12), selectedHover: ThemeColor(red: 0.95, green: 0.50, blue: 0.15, opacity: 0.18), bar: ThemeColor(hex: "12100C"), subtle: ThemeColor(red: 1, green: 0.8, blue: 0.5, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "2E2620"), hover: ThemeColor(hex: "48403A"), selected: ThemeColor(hex: "E88030"), focused: ThemeColor(hex: "E88030"), subtle: ThemeColor(red: 1, green: 0.8, blue: 0.5, opacity: 0.06), error: ThemeColor(hex: "E84040"), warning: ThemeColor(hex: "E8A030")),
        text: TextColors(primary: ThemeColor(hex: "F0E0CC"), secondary: ThemeColor(hex: "B09878"), tertiary: ThemeColor(hex: "7A6850"), quaternary: ThemeColor(hex: "504438"), onAccent: ThemeColor(hex: "1A1512"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "F0A050")),
        icons: IconColors(primary: ThemeColor(hex: "D0BCA0"), secondary: ThemeColor(hex: "7A6850"), tertiary: ThemeColor(hex: "504438"), onAccent: ThemeColor(hex: "1A1512")),
        accent: AccentColors(primary: ThemeColor(hex: "E88030"), hover: ThemeColor(hex: "F0A050"), active: ThemeColor(hex: "D06820"), subtle: ThemeColor(red: 0.91, green: 0.50, blue: 0.19, opacity: 0.15), muted: ThemeColor(red: 0.91, green: 0.50, blue: 0.19, opacity: 0.08)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "E84040"), subtle: ThemeColor(hex: "281010"), border: ThemeColor(red: 0.91, green: 0.25, blue: 0.25, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "E8A030"), subtle: ThemeColor(hex: "281C08"), border: ThemeColor(red: 0.91, green: 0.63, blue: 0.19, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "70BB50"), subtle: ThemeColor(hex: "182810"), border: ThemeColor(red: 0.44, green: 0.73, blue: 0.31, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "50A0CC"), subtle: ThemeColor(hex: "081C28"), border: ThemeColor(red: 0.31, green: 0.63, blue: 0.80, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "E88030"), scrollbarThumb: ThemeColor(hex: "383028"), scrollbarThumbHover: ThemeColor(hex: "48403A"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.91, green: 0.50, blue: 0.19, opacity: 0.30), searchMatchActive: ThemeColor(red: 0.91, green: 0.50, blue: 0.19, opacity: 0.60), dropTarget: ThemeColor(red: 0.91, green: 0.50, blue: 0.19, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "E88030")),
        terminal: TerminalColors(background: ThemeColor(hex: "1A1512"), foreground: ThemeColor(hex: "F0E0CC"), cursor: ThemeColor(hex: "E88030"), cursorText: ThemeColor(hex: "1A1512"), selection: ThemeColor(red: 0.91, green: 0.50, blue: 0.19, opacity: 0.20), ansi: AnsiPalette(black: ThemeColor(hex: "2E2620"), red: ThemeColor(hex: "E86050"), green: ThemeColor(hex: "88BB50"), yellow: ThemeColor(hex: "E8B840"), blue: ThemeColor(hex: "6098CC"), magenta: ThemeColor(hex: "C87088"), cyan: ThemeColor(hex: "60AABB"), white: ThemeColor(hex: "D0BCA0"), brightBlack: ThemeColor(hex: "504438"), brightRed: ThemeColor(hex: "F08878"), brightGreen: ThemeColor(hex: "A8DD70"), brightYellow: ThemeColor(hex: "F0D060"), brightBlue: ThemeColor(hex: "80B8EE"), brightMagenta: ThemeColor(hex: "E890A8"), brightCyan: ThemeColor(hex: "80CCDD"), brightWhite: ThemeColor(hex: "F8F0E0")))
    )

    // MARK: - 9. Neon Tokyo (Synthwave — hot pink and cyan on dark)
    static let neonTokyo = Theme(
        metadata: ThemeMetadata(id: "neon-tokyo", name: "Neon Tokyo", author: "Deck", version: 1, colorScheme: .dark, description: "Synthwave neon — hot pink and cyan on deep purple", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "0E0818"), inset: ThemeColor(hex: "080410"), elevated: ThemeColor(hex: "160E22"), overlay: ThemeColor(red: 0.04, green: 0.01, blue: 0.08, opacity: 0.75), hover: ThemeColor(hex: "1E142E"), active: ThemeColor(hex: "261A38"), selected: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.12), selectedHover: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.18), bar: ThemeColor(hex: "080410"), subtle: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "1E142E"), hover: ThemeColor(hex: "302050"), selected: ThemeColor(hex: "FF3399"), focused: ThemeColor(hex: "FF3399"), subtle: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.08), error: ThemeColor(hex: "FF3344"), warning: ThemeColor(hex: "FFAA00")),
        text: TextColors(primary: ThemeColor(hex: "F0E8FF"), secondary: ThemeColor(hex: "A090C0"), tertiary: ThemeColor(hex: "706088"), quaternary: ThemeColor(hex: "483E5C"), onAccent: ThemeColor(hex: "FFFFFF"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "00EEFF")),
        icons: IconColors(primary: ThemeColor(hex: "C8B8E0"), secondary: ThemeColor(hex: "706088"), tertiary: ThemeColor(hex: "483E5C"), onAccent: ThemeColor(hex: "FFFFFF")),
        accent: AccentColors(primary: ThemeColor(hex: "FF3399"), hover: ThemeColor(hex: "FF66BB"), active: ThemeColor(hex: "DD2080"), subtle: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.15), muted: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.06)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "FF3344"), subtle: ThemeColor(hex: "200808"), border: ThemeColor(red: 1, green: 0.2, blue: 0.27, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "FFAA00"), subtle: ThemeColor(hex: "201808"), border: ThemeColor(red: 1, green: 0.67, blue: 0, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "00FF88"), subtle: ThemeColor(hex: "002818"), border: ThemeColor(red: 0, green: 1, blue: 0.53, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "00EEFF"), subtle: ThemeColor(hex: "002028"), border: ThemeColor(red: 0, green: 0.93, blue: 1, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "FF3399"), scrollbarThumb: ThemeColor(hex: "1E142E"), scrollbarThumbHover: ThemeColor(hex: "302050"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.30), searchMatchActive: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.60), dropTarget: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "FF3399")),
        terminal: TerminalColors(background: ThemeColor(hex: "0E0818"), foreground: ThemeColor(hex: "F0E8FF"), cursor: ThemeColor(hex: "FF3399"), cursorText: ThemeColor(hex: "0E0818"), selection: ThemeColor(red: 1, green: 0.2, blue: 0.6, opacity: 0.20), ansi: AnsiPalette(black: ThemeColor(hex: "1E142E"), red: ThemeColor(hex: "FF3366"), green: ThemeColor(hex: "00FF88"), yellow: ThemeColor(hex: "FFDD00"), blue: ThemeColor(hex: "3388FF"), magenta: ThemeColor(hex: "FF33CC"), cyan: ThemeColor(hex: "00EEFF"), white: ThemeColor(hex: "C8B8E0"), brightBlack: ThemeColor(hex: "483E5C"), brightRed: ThemeColor(hex: "FF6688"), brightGreen: ThemeColor(hex: "66FFAA"), brightYellow: ThemeColor(hex: "FFEE44"), brightBlue: ThemeColor(hex: "66AAFF"), brightMagenta: ThemeColor(hex: "FF66DD"), brightCyan: ThemeColor(hex: "66F0FF"), brightWhite: ThemeColor(hex: "F8F0FF")))
    )

    // MARK: - 10. Moss (Deep forest green, earthy)
    static let moss = Theme(
        metadata: ThemeMetadata(id: "moss", name: "Moss", author: "Deck", version: 1, colorScheme: .dark, description: "Deep forest canopy — rich greens and earth tones", isBuiltIn: true),
        surfaces: SurfaceColors(primary: ThemeColor(hex: "0E1610"), inset: ThemeColor(hex: "0A100C"), elevated: ThemeColor(hex: "161E18"), overlay: ThemeColor(red: 0, green: 0.04, blue: 0.02, opacity: 0.70), hover: ThemeColor(hex: "1E2820"), active: ThemeColor(hex: "263028"), selected: ThemeColor(red: 0.3, green: 0.8, blue: 0.4, opacity: 0.10), selectedHover: ThemeColor(red: 0.3, green: 0.8, blue: 0.4, opacity: 0.16), bar: ThemeColor(hex: "0A100C"), subtle: ThemeColor(red: 0.3, green: 0.8, blue: 0.4, opacity: 0.03)),
        borders: BorderColors(primary: ThemeColor(hex: "1E2820"), hover: ThemeColor(hex: "304038"), selected: ThemeColor(hex: "4AAA60"), focused: ThemeColor(hex: "4AAA60"), subtle: ThemeColor(red: 0.3, green: 0.8, blue: 0.4, opacity: 0.06), error: ThemeColor(hex: "D85040"), warning: ThemeColor(hex: "D0A030")),
        text: TextColors(primary: ThemeColor(hex: "E0EAE2"), secondary: ThemeColor(hex: "90A894"), tertiary: ThemeColor(hex: "607868"), quaternary: ThemeColor(hex: "405048"), onAccent: ThemeColor(hex: "0E1610"), onError: ThemeColor(hex: "FFFFFF"), link: ThemeColor(hex: "60CC78")),
        icons: IconColors(primary: ThemeColor(hex: "B8D0BC"), secondary: ThemeColor(hex: "607868"), tertiary: ThemeColor(hex: "405048"), onAccent: ThemeColor(hex: "0E1610")),
        accent: AccentColors(primary: ThemeColor(hex: "4AAA60"), hover: ThemeColor(hex: "60CC78"), active: ThemeColor(hex: "388848"), subtle: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.15), muted: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.08)),
        status: StatusColors(error: StatusColor(primary: ThemeColor(hex: "D85040"), subtle: ThemeColor(hex: "281010"), border: ThemeColor(red: 0.85, green: 0.31, blue: 0.25, opacity: 0.40)), warning: StatusColor(primary: ThemeColor(hex: "D0A030"), subtle: ThemeColor(hex: "201C08"), border: ThemeColor(red: 0.82, green: 0.63, blue: 0.19, opacity: 0.40)), success: StatusColor(primary: ThemeColor(hex: "4AAA60"), subtle: ThemeColor(hex: "0A200E"), border: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.40)), info: StatusColor(primary: ThemeColor(hex: "40A0C8"), subtle: ThemeColor(hex: "081820"), border: ThemeColor(red: 0.25, green: 0.63, blue: 0.78, opacity: 0.40))),
        interactive: InteractiveColors(focusRing: ThemeColor(hex: "4AAA60"), scrollbarThumb: ThemeColor(hex: "263028"), scrollbarThumbHover: ThemeColor(hex: "304038"), scrollbarTrack: ThemeColor(red: 0, green: 0, blue: 0, opacity: 0), searchMatch: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.30), searchMatchActive: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.60), dropTarget: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.10), dropTargetBorder: ThemeColor(hex: "4AAA60")),
        terminal: TerminalColors(background: ThemeColor(hex: "0E1610"), foreground: ThemeColor(hex: "E0EAE2"), cursor: ThemeColor(hex: "4AAA60"), cursorText: ThemeColor(hex: "0E1610"), selection: ThemeColor(red: 0.29, green: 0.67, blue: 0.38, opacity: 0.20), ansi: AnsiPalette(black: ThemeColor(hex: "1E2820"), red: ThemeColor(hex: "D86050"), green: ThemeColor(hex: "50CC68"), yellow: ThemeColor(hex: "D0B840"), blue: ThemeColor(hex: "5090CC"), magenta: ThemeColor(hex: "A870B0"), cyan: ThemeColor(hex: "50B8A8"), white: ThemeColor(hex: "B8D0BC"), brightBlack: ThemeColor(hex: "405048"), brightRed: ThemeColor(hex: "F08070"), brightGreen: ThemeColor(hex: "70EE88"), brightYellow: ThemeColor(hex: "E8D860"), brightBlue: ThemeColor(hex: "70B0EE"), brightMagenta: ThemeColor(hex: "C890D0"), brightCyan: ThemeColor(hex: "70D8C8"), brightWhite: ThemeColor(hex: "F0F8F2")))
    )
}
